<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Giovani Jovanotti</name>
   <tag></tag>
   <elementGuidId>61a60a00-ea88-4a4e-8442-de70e85eb6e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p/i[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de616e67-812a-4699-93fb-7abf900e1d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Giovani_Jovanotti</value>
      <webElementGuid>7c247211-d0b5-4456-928b-5afa5ad1dad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giovani Jovanotti</value>
      <webElementGuid>cc2f0bb0-367c-40aa-b7fe-83796ca51d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-parser-output&quot;]/p[1]/i[2]/a[1]</value>
      <webElementGuid>5ad51259-b42c-47b2-8cd4-b9418952a120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p/i[2]/a</value>
      <webElementGuid>22dd8840-8f2e-4d16-b2e5-9274e2512e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Giovani Jovanotti')])[2]</value>
      <webElementGuid>eadb2252-a1ae-4d83-8606-a5fce9afca94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jovanotti'])[2]/following::a[1]</value>
      <webElementGuid>0c02e712-0950-4272-8871-61d641c98535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciao mamma'])[3]/following::a[2]</value>
      <webElementGuid>057df9a4-f19f-4711-b669-6e0b308bab87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorenzo 1990-1995'])[1]/preceding::a[3]</value>
      <webElementGuid>fb5599f9-19a8-489f-9299-095e706c2b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='film'])[1]/preceding::a[4]</value>
      <webElementGuid>abfb4578-7d70-4097-a0b7-8ee892ad1f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wiki/Giovani_Jovanotti')])[2]</value>
      <webElementGuid>2481cc0e-0341-45c0-8afe-ebfbeb490208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]/a</value>
      <webElementGuid>a7b6be2e-55b2-4a1e-88e8-7a0fa35c2951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Giovani_Jovanotti' and (text() = 'Giovani Jovanotti' or . = 'Giovani Jovanotti')]</value>
      <webElementGuid>be1c86d5-94a1-4086-bea8-089ee1fe47c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
